spring:
  profiles: pro
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.234.78.87:3306/blog?allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
server:
  port: 80