spring:
  profiles: dev
  # 数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 8080
